CMAKE_MINIMUM_REQUIRED(VERSION 3.15)

PROJECT(
    tiny_thread_pool
    LANGUAGES CXX
)

SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_VISIBILITY_PRESET hidden)
SET(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)
SET(CMAKE_CXX_FLAG_DEBUG "-O0 -Wall -g -ggdb")

if (NOT CMAKE_BUILD_TYPE)
    SET(CMAKE_BUILD_TYPE Debug)
endif()

INCLUDE(GenerateExportHeader)

ADD_LIBRARY(${PROJECT_NAME})
GENERATE_EXPORT_HEADER(${PROJECT_NAME} EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/include/tiny_thread_pool_export.hpp)
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE true)
TARGET_SOURCES(
    ${PROJECT_NAME}
    PRIVATE "src/tiny_thread_pool.cpp"
)
TARGET_INCLUDE_DIRECTORIES(
    ${PROJECT_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
        $<INSTALL_INTERFACE:include>
)

INSTALL(
    TARGETS ${PROJECT_NAME}
    EXPORT TinyThreadPool
    LIBRARY DESTINATION lib
)
INSTALL(
    FILES src/tiny_thread_pool.hpp
    DESTINATION include
)
INSTALL(
    EXPORT TinyThreadPool
    FILE tiny_thread_pool-config.cmake
    NAMESPACE TinyThreadPool::
    DESTINATION lib/cmake/tiny_thread_pool
)

if (CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    ADD_EXECUTABLE(test_${PROJECT_NAME} "tests/test_tiny_thread_pool.cpp")
    TARGET_LINK_LIBRARIES(test_${PROJECT_NAME} PRIVATE ${PROJECT_NAME})

    ENABLE_TESTING()
    ADD_TEST(
        NAME test_${PROJECT_NAME}
        COMMAND $<TARGET_FILE:test_${PROJECT_NAME}>
    )
endif()
